import type { BookMeta } from '../types/bible';

export const BIBLE_BOOKS: BookMeta[] = [
  { name: 'Genesis', testament: 'OT', chapters: 50, abbreviation: 'Gen' },
  { name: 'Exodus', testament: 'OT', chapters: 40, abbreviation: 'Exod' },
  { name: 'Leviticus', testament: 'OT', chapters: 27, abbreviation: 'Lev' },
  { name: 'Numbers', testament: 'OT', chapters: 36, abbreviation: 'Num' },
  { name: 'Deuteronomy', testament: 'OT', chapters: 34, abbreviation: 'Deut' },
  { name: 'Joshua', testament: 'OT', chapters: 24, abbreviation: 'Josh' },
  { name: 'Judges', testament: 'OT', chapters: 21, abbreviation: 'Judg' },
  { name: 'Ruth', testament: 'OT', chapters: 4, abbreviation: 'Ruth' },
  { name: '1 Samuel', testament: 'OT', chapters: 31, abbreviation: '1Sam' },
  { name: '2 Samuel', testament: 'OT', chapters: 24, abbreviation: '2Sam' },
  { name: '1 Kings', testament: 'OT', chapters: 22, abbreviation: '1Kgs' },
  { name: '2 Kings', testament: 'OT', chapters: 25, abbreviation: '2Kgs' },
  { name: '1 Chronicles', testament: 'OT', chapters: 29, abbreviation: '1Chr' },
  { name: '2 Chronicles', testament: 'OT', chapters: 36, abbreviation: '2Chr' },
  { name: 'Ezra', testament: 'OT', chapters: 10, abbreviation: 'Ezra' },
  { name: 'Nehemiah', testament: 'OT', chapters: 13, abbreviation: 'Neh' },
  { name: 'Esther', testament: 'OT', chapters: 10, abbreviation: 'Esth' },
  { name: 'Job', testament: 'OT', chapters: 42, abbreviation: 'Job' },
  { name: 'Psalms', testament: 'OT', chapters: 150, abbreviation: 'Ps' },
  { name: 'Proverbs', testament: 'OT', chapters: 31, abbreviation: 'Prov' },
  { name: 'Ecclesiastes', testament: 'OT', chapters: 12, abbreviation: 'Eccl' },
  { name: 'Song of Solomon', testament: 'OT', chapters: 8, abbreviation: 'Song' },
  { name: 'Isaiah', testament: 'OT', chapters: 66, abbreviation: 'Isa' },
  { name: 'Jeremiah', testament: 'OT', chapters: 52, abbreviation: 'Jer' },
  { name: 'Lamentations', testament: 'OT', chapters: 5, abbreviation: 'Lam' },
  { name: 'Ezekiel', testament: 'OT', chapters: 48, abbreviation: 'Ezek' },
  { name: 'Daniel', testament: 'OT', chapters: 12, abbreviation: 'Dan' },
  { name: 'Hosea', testament: 'OT', chapters: 14, abbreviation: 'Hos' },
  { name: 'Joel', testament: 'OT', chapters: 3, abbreviation: 'Joel' },
  { name: 'Amos', testament: 'OT', chapters: 9, abbreviation: 'Amos' },
  { name: 'Obadiah', testament: 'OT', chapters: 1, abbreviation: 'Obad' },
  { name: 'Jonah', testament: 'OT', chapters: 4, abbreviation: 'Jonah' },
  { name: 'Micah', testament: 'OT', chapters: 7, abbreviation: 'Mic' },
  { name: 'Nahum', testament: 'OT', chapters: 3, abbreviation: 'Nah' },
  { name: 'Habakkuk', testament: 'OT', chapters: 3, abbreviation: 'Hab' },
  { name: 'Zephaniah', testament: 'OT', chapters: 3, abbreviation: 'Zeph' },
  { name: 'Haggai', testament: 'OT', chapters: 2, abbreviation: 'Hag' },
  { name: 'Zechariah', testament: 'OT', chapters: 14, abbreviation: 'Zech' },
  { name: 'Malachi', testament: 'OT', chapters: 4, abbreviation: 'Mal' },
  { name: 'Matthew', testament: 'NT', chapters: 28, abbreviation: 'Matt' },
  { name: 'Mark', testament: 'NT', chapters: 16, abbreviation: 'Mark' },
  { name: 'Luke', testament: 'NT', chapters: 24, abbreviation: 'Luke' },
  { name: 'John', testament: 'NT', chapters: 21, abbreviation: 'John' },
  { name: 'Acts', testament: 'NT', chapters: 28, abbreviation: 'Acts' },
  { name: 'Romans', testament: 'NT', chapters: 16, abbreviation: 'Rom' },
  { name: '1 Corinthians', testament: 'NT', chapters: 16, abbreviation: '1Cor' },
  { name: '2 Corinthians', testament: 'NT', chapters: 13, abbreviation: '2Cor' },
  { name: 'Galatians', testament: 'NT', chapters: 6, abbreviation: 'Gal' },
  { name: 'Ephesians', testament: 'NT', chapters: 6, abbreviation: 'Eph' },
  { name: 'Philippians', testament: 'NT', chapters: 4, abbreviation: 'Phil' },
  { name: 'Colossians', testament: 'NT', chapters: 4, abbreviation: 'Col' },
  { name: '1 Thessalonians', testament: 'NT', chapters: 5, abbreviation: '1Thess' },
  { name: '2 Thessalonians', testament: 'NT', chapters: 3, abbreviation: '2Thess' },
  { name: '1 Timothy', testament: 'NT', chapters: 6, abbreviation: '1Tim' },
  { name: '2 Timothy', testament: 'NT', chapters: 4, abbreviation: '2Tim' },
  { name: 'Titus', testament: 'NT', chapters: 3, abbreviation: 'Titus' },
  { name: 'Philemon', testament: 'NT', chapters: 1, abbreviation: 'Phlm' },
  { name: 'Hebrews', testament: 'NT', chapters: 13, abbreviation: 'Heb' },
  { name: 'James', testament: 'NT', chapters: 5, abbreviation: 'Jas' },
  { name: '1 Peter', testament: 'NT', chapters: 5, abbreviation: '1Pet' },
  { name: '2 Peter', testament: 'NT', chapters: 3, abbreviation: '2Pet' },
  { name: '1 John', testament: 'NT', chapters: 5, abbreviation: '1John' },
  { name: '2 John', testament: 'NT', chapters: 1, abbreviation: '2John' },
  { name: '3 John', testament: 'NT', chapters: 1, abbreviation: '3John' },
  { name: 'Jude', testament: 'NT', chapters: 1, abbreviation: 'Jude' },
  { name: 'Revelation', testament: 'NT', chapters: 22, abbreviation: 'Rev' },
];

export const OT_BOOKS = BIBLE_BOOKS.filter(b => b.testament === 'OT');
export const NT_BOOKS = BIBLE_BOOKS.filter(b => b.testament === 'NT');

export function getBookMeta(name: string): BookMeta | undefined {
  return BIBLE_BOOKS.find(b => b.name === name);
}
