export const HIGHLIGHT_COLORS = [
  { name: 'Yellow', value: '#FFEAA7', class: 'bg-highlight-yellow' },
  { name: 'Green', value: '#A8F0C6', class: 'bg-highlight-green' },
  { name: 'Blue', value: '#A0D2FF', class: 'bg-highlight-blue' },
  { name: 'Pink', value: '#FFADC6', class: 'bg-highlight-pink' },
  { name: 'Purple', value: '#D4A5FF', class: 'bg-highlight-purple' },
];

export const MOOD_OPTIONS = [
  { emoji: '😌', label: 'Peaceful' },
  { emoji: '😊', label: 'Joyful' },
  { emoji: '🙏', label: 'Grateful' },
  { emoji: '😰', label: 'Anxious' },
  { emoji: '😔', label: 'Heavy' },
  { emoji: '😕', label: 'Confused' },
  { emoji: '🌱', label: 'Hopeful' },
  { emoji: '😤', label: 'Restless' },
];

export const DEFAULT_TAGS = [
  { name: 'Faith', color: '#007AFF' },
  { name: 'Guidance', color: '#34C759' },
  { name: 'Conviction', color: '#FF2D55' },
  { name: 'Challenge', color: '#FF9500' },
  { name: 'Comfort', color: '#5AC8FA' },
  { name: 'Prophecy', color: '#0051D5' },
  { name: 'Grace', color: '#64B5F6' },
  { name: 'Wisdom', color: '#FF6482' },
];

export const WEEKLY_PROMPTS = [
  "What did God teach you this week?",
  "Which verse spoke to you most powerfully this week?",
  "How did your prayer life change this week?",
  "Where did you see God at work this week?",
  "What area of your life is God refining right now?",
  "What truth did you discover that challenged your perspective?",
  "How did Scripture comfort you during a difficult moment this week?",
  "What is God calling you to surrender this week?",
  "How has your understanding of God's character deepened?",
  "What spiritual pattern are you noticing in your life?",
  "Where did you experience God's grace most vividly this week?",
  "What verse would you share with someone going through what you faced this week?",
  "How has your gratitude grown through this week's study?",
  "What conviction has the Holy Spirit placed on your heart?",
  "What prayer was answered this week — and how did it shape your faith?",
  "How did you apply Scripture to a real situation this week?",
  "What is the theme God seems to be weaving through your recent readings?",
  "What did you learn about yourself through the lens of Scripture?",
  "How has worship shaped your week?",
  "What step of obedience is God asking you to take?",
  "What promise of God anchored you this week?",
  "How have you grown in patience or endurance through this week's study?",
  "What aspect of Jesus' character stood out to you this week?",
  "Where do you need to trust God more deeply?",
  "How has community strengthened your faith this week?",
  "What old habit is God replacing with a new one?",
  "What did you discover about prayer that surprised you?",
  "How has forgiving someone (or being forgiven) shaped your week?",
  "What spiritual fruit has grown the most in you recently?",
  "What would change if you fully believed the verse that marked you this week?",
  "How has studying Scripture affected your relationships this week?",
  "What fear is God asking you to release?",
  "Where did you experience joy in the midst of difficulty?",
  "How is God preparing you for something ahead?",
  "What truth did you need to hear most this week — and how did God deliver it?",
  "How has your view of eternity shifted through this week's readings?",
  "What act of service or love did Scripture inspire in you this week?",
  "How did rest and stillness before God impact your study?",
  "What spiritual discipline do you want to deepen next week?",
  "What would you tell your past self about what God has shown you this week?",
  "How has Scripture shaped the way you handle conflict?",
  "What new name or attribute of God have you discovered?",
  "Where did humility deepen your understanding this week?",
  "How did you encounter God outside of your study time?",
  "What burden has God lifted as you've spent time in His Word?",
  "How has generosity been part of your spiritual growth this week?",
  "What does faithfulness look like in your current season?",
  "How has studying together with others enriched your understanding?",
  "What is the biggest way your heart has changed this week?",
  "What are you most looking forward to learning next week?",
  "How has this week's study prepared you for worship this Sunday?",
  "What legacy of faith are you building through your daily practice?",
];
